os: linux
dist: bionic
language: cpp

services:
  - docker

before_install:
  - sudo apt-get update

before_script:
  - docker build -t driver-management .

script:
  - docker run --name dmcont -t -d --volume="$HOME/.Xauthority:/root/.Xauthority:rw" driver-management
  - echo ${INTEL_OPENVINO_DIR}

after_script:
  - docker ps
  - docker system prune -a -f
