os: linux
dist: bionic
language: cpp

services:
  - docker

before_install:
  - sudo apt-get update

before_script:
  - docker build -t driver-management .

script:
  - docker run --name dmcont -t -d --volume="$HOME/.Xauthority:/root/.Xauthority:rw" driver-management
  - docker exec dmcont bash -c 'cd /app/DriverBehavior/build && curl -s -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip -o sonarscanner.zip && unzip -qq sonarscanner.zip && export PATH=$PATH:sonar-scanner-4.2.0.1873-linux/bin/ && apt-get install -y openjdk-8-jre && sonar-scanner -Dsonar.organization=incluit -Dsonar.projectKey=incluit_OpenVino-Driver-Management -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectBaseDir=../src -Dproject.home=../src -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.login=166e8c3490138565f7b424de56b7dd6abe97beec'

after_script:
  - docker ps
  - docker system prune -a -f
