os: linux
dist: bionic
language: cpp

services:
  - docker

jobs:
  include:
    - stage: Install
      script: sudo apt-get update

    - stage: Docker
      script:
           - docker build -t driver-management .
           - docker run --name dmcont -t -d --volume="$HOME/.Xauthority:/root/.Xauthority:rw" driver-management
           - docker exec dmcont bash -c 'source ${INTEL_OPENVINO_DIR}/bin/setupvars.sh && cd /app/DriverBehavior/build && curl -s -L https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -o buildwrapper.zip && unzip -qq buildwrapper.zip && export PATH=$PATH:build-wrapper-linux-x86/ && build-wrapper-linux-x86-64 --out-dir bw-output make clean all'
           - docker exec dmcont bash -c 'cd /app/DriverBehavior/build && curl -s -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip -o sonarscanner.zip && unzip -qq sonarscanner.zip && export PATH=$PATH:sonar-scanner-4.2.0.1873-linux/bin/ && apt-get install -y openjdk-8-jre && sonar-scanner -Dsonar.organization=incluit -Dsonar.projectKey=incluit_OpenVino-Driver-Management -Dsonar.sources=. -Dsonar.projectBaseDir=../src -Dproject.home=../src -Dsonar.host.url=https://sonarcloud.io -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.login=fadffa518eb70a1f8dd7375d4719240d1d51c7b9'
           - docker ps
           - docker images
           - docker system prune -a -f
           - echo $TRAVIS_JOB_ID ' this is the job id'
           - echo $TRAVIS_JOB_NUMBER ' This is the job number'
           - echo $TRAVIS_BUILD_NUMBER ' This is the build number'

    - stage: Validation
      script:
           - docker images
           - echo $TRAVIS_JOB_ID ' this is the job id'
           - echo $TRAVIS_JOB_NUMBER ' This is the job number'
           - echo $TRAVIS_BUILD_NUMBER ' This is the build number'