os: linux
dist: bionic
language: cpp

services:
  - docker

jobs:
  include:
    - stage: Install
      script: sudo apt-get update
    - stage: Docker
      script: docker build -t driver-management .
    - stage: Validate
      script: docker ps
              docker images
              docker system prune -a -f