os: linux
dist: bionic
language: cpp

services:
  - docker

before_install:
  - sudo apt-get update

before_script:
  - docker build -t Driver-Management .

script:
  - echo "Testing the pipeline"

after_script:
  - pwd
