# OpenVino-Driver-Management
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title: Table of Contents

toc::[]

== Introduction

TBD.

== Use cases

=== Driver Behaviour
Discover more about this use case https://github.com/incluit/OpenVino-Driver-Management/tree/master/DriverBehavior[here].

=== Action Recognition
Discover more about this use case https://github.com/incluit/OpenVino-Driver-Management/tree/master/ActionRecognition[here].

=== User Interface
Discover more about this use case https://github.com/incluit/OpenVino-Driver-Management/tree/master/UI[here].

== Prerequisites

=== Hardware

* Optional:

**  USB camera - Standard USB Video Class (UVC) camera.

** Intel® Core™ CPU with integrated graphics.

** Intel® Movidius™ Neural Compute Stick

=== Software

* Docker. To install on Ubuntu, run:

[source,bash]
----
sudo snap install docker

sudo groupadd docker

sudo usermod -aG docker $USER
----


== Installation

**1.** Clone the repository at desired location:

[source,bash]
----
git clone https://github.com/incluit/OpenVino-Driver-Management.git
----

**2.** Change to the top git repository:

[source,bash]
----
cd OpenVino-Driver-Management
----

**3.** Build the docker:
[source,bash]
----
make docker-build
----

**4.** Run the  docker:
[source,bash]
----
make docker-run
----

== Run

**1.** Start the docker:
[source,bash]
----
make docker-start
----

**2.** Inside the docker run:
[source,bash]
----
make run
----

**3.** AWS:

Add the certificates of AWS in the UI

After adding the certificates go to "Dashboard" tab and click on "log in".

== Docker Options

* Stop the docker container
[source,bash]
----
make docker-stop
----

* Remove the docker container
[source,bash]
----
make docker-remove
----

== To Do

* [ ] Intrduction in README file.
* [ ] Create a Docker image of the project, upload to Docker Hub and add this option in the Readme file.
